### ISSUE TITLE
import titan_engine.teSdk

### ISSUE THREAD

**Issue by jcarndt** [d00rt/emotet_research#1]
First, thanks for all of this work. This looks like an awesome tool.

It looks like it's having an issue when it tries to import titan_engine.teSdk. Pretty sure I've got everything set up correctly... but I'll accept all blame if I don't.

C:\Users\REM\Desktop\emotet_research-master\unpacker\src>python main.py -h
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from unpacker import deEmotet
  File "C:\Users\REM\Desktop\emotet_research-master\unpacker\src\unpacker.py", line 3, in <module>
    from titan_engine.teSdk import *
  File "C:\Users\REM\Desktop\emotet_research-master\unpacker\src\titan_engine\teSdk.py", line 3, in <module>
    TE = windll.LoadLibrary("TitanEngine.dll")
  File "C:\Python27\lib\ctypes\__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by paladin316** [comment]
if you are running a  Win 64 bit OS you will need to use the 64 bit version of TitanEngine. This should solve the error you posted.

**Comment by paladin316** [comment]
@jammy570 for this to work correctly you will need to run this in an X86 Win VM. This will not work on a Win 64 bit OS.

**Comment by d00rt** [comment]
Yes, Thank you @paladin316, The TitanEngine.dll that it is in the repo is just for x86 OS. Currently I upload the repo with both x86 and x64 TitanEngine dll. If you are running it in a x64 OS you have to use x64 dll or run with a python x86 instance

Thank you :)
