### ISSUE TITLE
Unpacker Doesn't work on new version of Emotet

### ISSUE THREAD

**Issue by aspir** [d00rt/emotet_research#2]
There are new Emotet samples in the wild. 
Here are some SHA265 of new samples from 12/12/18:

0a05b153fba825174e967e9bdc01e9dd84088183ecb5a992bb060c7af3f6a2f9
dfa6e344f452e0a1ca137397ffac9031909e2e5429cf335ea7f5cd73ef74f305
ea82cee83afb1302b65e9f13da221416d327845964744c301ede6077a74491af
884cd4e40a936258a5e6874c4a817a80dcf6fda261c6e7d4af2b6f29a0ef4d32
d5363454d1ea6d135de00d040738098a4f24e91aacde50a46dd062ee7718b39e
16dacbc9c55450010e0d9a2f53e8e1bc1b5a63b0cdda94c9b239bb2142b69688
b24245d4b8476f54353d0a2ed3d2aed641a83ea7c2a218c713ee23e90b4362ea
529c1f84b2e0664827c44268359cb4c72ad64d2feac48b5cd5e7ad1d904fe835
f3f0ca46191b8c737f629ab1e6c4c955b26f53a5d672fdd07629b78fd27f5fdd
849ffb655660d7350b8c89bb965e2e1ca84ba3f8c7d50e453e33af0d54569cac   
a31bab8ddec755b0f57c220cc7fe5b17a2105a078c1cbd2452533cbcdf04f7b4
4a3be01a847fa4ddc2f8c7a398733fd98b47cce9b2092a53c671c4eaf6649df1
57d7be9f7cfffd7a61ffd2af6abb10e672aa9f553564f03338c3dddb7af92f0b
d9822b97ff1ec9142ca2eb86909ce264e40d03b377d8b158ac0b648ac5ea1943
d810a3f8b7a7ff21699f298a1c1f7860241e715f7c73e1bfe62a57d971517fae

**Comment by d00rt** [comment]
I just checked the first sample 
0a05b153fba825174e967e9bdc01e9dd84088183ecb5a992bb060c7af3f6a2f9
And it works correctly.

Try to use it in a Win 7 32bits system. I developed the tool in that system 

![image](https://user-images.githubusercontent.com/30732868/50609970-9b6bd580-0ed1-11e9-836b-13b8b732a77b.png)

Anyway you can write the log in verbose mode?

Thank you :D

**Comment by aspir** [comment]
The program crashing on specific hash: a31bab8ddec755b0f57c220cc7fe5b17a2105a078c1cbd2452533cbcdf04f7b4

Here is the crash info:

Problem signature:
  Problem Event Name:	BEX
  Application Name:	a31bab8ddec755b0f57c220cc7fe5b17a2105a078c1cbd2452533cbcdf04f7b4
  Application Version:	5.20.3.0
  Application Timestamp:	5c114053
  Fault Module Name:	StackHash_c247
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	00000000
  Exception Code:	c0000005
  Exception Data:	00000008
  OS Version:	6.1.7600.2.0.0.768.5
  Locale ID:	1033
  Additional Information 1:	c247
  Additional Information 2:	c2474e8ce10d09ef9f60f4c7e88d526f
  Additional Information 3:	8d9f
  Additional Information 4:	8d9fdbcb2fdb88bc0add1863c966d452

**Comment by d00rt** [comment]
This bug that many people are reporting to me, over which I have no control. I talked to some friends (since I don't have time to look at it) and they told me that it could be some problem of the TE debugger that doesn't recognize well some OP CODES.
